name: Test

on:
  pull_request:
  push:
    branches: [master]
    paths:
      - 'packages/motion/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      
      - name: Build Motion
        run: pnpm build
        
      - name: Run tests
        run: pnpm test


      # - name: Build Docs
      #   run: pnpm docs:build

      #   # Run a action to publish docs
      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1.5.0
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: motion-vue
      #     directory: dist
      #     # Optional: Enable this if you want to have GitHub Deployments triggered
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     # Optional: Switch what branch you are publishing to.
      #     # By default this will be the branch which triggered this workflow
      #     # branch: main
      #     # Optional: Change the working directory
      #     workingDirectory: docs
      #     wranglerVersion: '3'
